/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Admin;

import javax.swing.JFrame;

/**
 *
 * @author ACER
 */
public class ViewMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewHalaman
     */
    public ViewMenuAdmin() {
        initComponents();
        setTitle("Menu Admin");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        tombolMenu = new javax.swing.JButton();
        navbar = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        tombolLogout = new javax.swing.JButton();
        tombolRiwayat = new javax.swing.JButton();
        latar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin");
        setBackground(new java.awt.Color(160, 130, 120));
        setPreferredSize(new java.awt.Dimension(540, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(540, 390));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setLayout(null);

        tombolMenu.setBackground(new java.awt.Color(191, 172, 165));
        tombolMenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tombolMenu.setText("Pendataan Menu");
        tombolMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolMenuActionPerformed(evt);
            }
        });
        panel.add(tombolMenu);
        tombolMenu.setBounds(180, 100, 180, 60);

        navbar.setBackground(new java.awt.Color(159, 130, 120));
        navbar.setLayout(null);

        labelLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelLogin.setText("Menu Admin");
        navbar.add(labelLogin);
        labelLogin.setBounds(200, 20, 150, 29);

        panel.add(navbar);
        navbar.setBounds(0, 0, 530, 70);

        tombolLogout.setBackground(new java.awt.Color(191, 172, 165));
        tombolLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tombolLogout.setText("Logout");
        tombolLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLogoutActionPerformed(evt);
            }
        });
        panel.add(tombolLogout);
        tombolLogout.setBounds(180, 260, 180, 60);

        tombolRiwayat.setBackground(new java.awt.Color(191, 172, 165));
        tombolRiwayat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tombolRiwayat.setText("Riwayat Order");
        tombolRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolRiwayatActionPerformed(evt);
            }
        });
        panel.add(tombolRiwayat);
        tombolRiwayat.setBounds(180, 180, 180, 60);

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        panel.add(latar);
        latar.setBounds(0, 0, 530, 370);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 530, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolMenuActionPerformed
        dispose();
        new ViewDataMenu();
    }//GEN-LAST:event_tombolMenuActionPerformed

    private void tombolLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLogoutActionPerformed
        dispose();
        new ViewHalamanLogin().setVisible(true);
    }//GEN-LAST:event_tombolLogoutActionPerformed

    private void tombolRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRiwayatActionPerformed
        dispose();
        new ViewRiwayat();
    }//GEN-LAST:event_tombolRiwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel latar;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel panel;
    private javax.swing.JButton tombolLogout;
    private javax.swing.JButton tombolMenu;
    private javax.swing.JButton tombolRiwayat;
    // End of variables declaration//GEN-END:variables
}
