package View.User;

import Controller.ControllerMenu;
import Controller.ControllerRiwayat;
import Model.Riwayat.ModelRiwayat;

public class ViewHalamanResult extends javax.swing.JFrame {

    ControllerMenu controller;
    ControllerRiwayat controller1;
    ModelRiwayat data = new ModelRiwayat();
    int idRiwayat;

    public ViewHalamanResult(ModelRiwayat riwayat, int id) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        
        this.data=riwayat;
        this.idRiwayat = id;
        this.controller = new ControllerMenu(this);
        this.controller1 = new ControllerRiwayat(this);
        
        getOutputNama();
        getOutputMenu();
        getOutputHotIce();
        getOutputSweetness();
        getOutputSize();
        getOutputDairy();
        getOutputTopping();
        getOutputNotes();
        getHargaDefault();
        getHargaSize();
        getHargaDairy();
        getHargaTopping();
        getHargaTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputNama = new javax.swing.JLabel();
        panelHarga = new javax.swing.JPanel();
        panelDairy = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        outputDairy = new javax.swing.JLabel();
        panelHotIce = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        outputHotIce = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        outputMenu = new javax.swing.JLabel();
        panelNote = new javax.swing.JPanel();
        labelNote = new javax.swing.JLabel();
        outputNotes = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        labelSweetness = new javax.swing.JLabel();
        labelTopping = new javax.swing.JLabel();
        outputSize = new javax.swing.JLabel();
        outputSweetness = new javax.swing.JLabel();
        outputTopping = new javax.swing.JLabel();
        panelTotalPrice = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        labelHargaDefault = new javax.swing.JLabel();
        labelHargaSize = new javax.swing.JLabel();
        labelHargaDairy = new javax.swing.JLabel();
        labelHargaTopping = new javax.swing.JLabel();
        hargaDefault = new javax.swing.JLabel();
        hargaSize = new javax.swing.JLabel();
        hargaDairy = new javax.swing.JLabel();
        hargaTopping = new javax.swing.JLabel();
        hargaTotal = new javax.swing.JLabel();
        labelHargaTotal = new javax.swing.JLabel();
        tombolGrab = new javax.swing.JButton();
        latar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outputNama.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        outputNama.setText("Here's Your Order");
        getContentPane().add(outputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 400, 50));

        panelHarga.setBackground(new java.awt.Color(255, 255, 255));

        panelDairy.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Dairy");

        javax.swing.GroupLayout panelDairyLayout = new javax.swing.GroupLayout(panelDairy);
        panelDairy.setLayout(panelDairyLayout);
        panelDairyLayout.setHorizontalGroup(
            panelDairyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDairyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        panelDairyLayout.setVerticalGroup(
            panelDairyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDairyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDairyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputDairy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDairyLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        panelHotIce.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Hot/Ice");

        javax.swing.GroupLayout panelHotIceLayout = new javax.swing.GroupLayout(panelHotIce);
        panelHotIce.setLayout(panelHotIceLayout);
        panelHotIceLayout.setHorizontalGroup(
            panelHotIceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotIceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputHotIce, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelHotIceLayout.setVerticalGroup(
            panelHotIceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHotIceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHotIceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputHotIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        panelMenu.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Menu");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        labelNote.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNote.setText("Note");

        outputNotes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelNoteLayout = new javax.swing.GroupLayout(panelNote);
        panelNote.setLayout(panelNoteLayout);
        panelNoteLayout.setHorizontalGroup(
            panelNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelNoteLayout.setVerticalGroup(
            panelNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoteLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNote, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        labelSize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSize.setText("Size");

        labelSweetness.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSweetness.setText("Sweetness Level");

        labelTopping.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTopping.setText("Topping");

        panelTotalPrice.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Total Price");

        labelHargaDefault.setText("Default");

        labelHargaSize.setText("Size");

        labelHargaDairy.setText("Dairy");

        labelHargaTopping.setText("Topping");

        hargaTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        labelHargaTotal.setText("Total");

        javax.swing.GroupLayout panelTotalPriceLayout = new javax.swing.GroupLayout(panelTotalPrice);
        panelTotalPrice.setLayout(panelTotalPriceLayout);
        panelTotalPriceLayout.setHorizontalGroup(
            panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPriceLayout.createSequentialGroup()
                .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTotalPriceLayout.createSequentialGroup()
                        .addContainerGap(9, Short.MAX_VALUE)
                        .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTotalPriceLayout.createSequentialGroup()
                                    .addGap(276, 276, 276)
                                    .addComponent(labelHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelHargaSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelHargaTopping, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelHargaDefault, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTotalPriceLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHargaDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaSize, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        panelTotalPriceLayout.setVerticalGroup(
            panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPriceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelHargaDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHargaSize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHargaDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHargaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(panelTotalPriceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hargaDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaSize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaDairy, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelHargaLayout = new javax.swing.GroupLayout(panelHarga);
        panelHarga.setLayout(panelHargaLayout);
        panelHargaLayout.setHorizontalGroup(
            panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDairy, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(panelHotIce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(panelNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHargaLayout.createSequentialGroup()
                .addGroup(panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHargaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelSweetness, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputSweetness, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputSize, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        panelHargaLayout.setVerticalGroup(
            panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHargaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelSize))
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHotIce, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGroup(panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelSweetness))
                    .addGroup(panelHargaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputSweetness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDairy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(panelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTopping)
                    .addComponent(outputTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
        );

        getContentPane().add(panelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 440));

        tombolGrab.setBackground(new java.awt.Color(255, 255, 102));
        tombolGrab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tombolGrab.setText("Grab Another One!");
        tombolGrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolGrabActionPerformed(evt);
            }
        });
        getContentPane().add(tombolGrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, 42));

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        latar.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(latar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1000, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolGrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolGrabActionPerformed
        new ViewHalamanOrder().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolGrabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaDairy;
    private javax.swing.JLabel hargaDefault;
    private javax.swing.JLabel hargaSize;
    private javax.swing.JLabel hargaTopping;
    private javax.swing.JLabel hargaTotal;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelHargaDairy;
    private javax.swing.JLabel labelHargaDefault;
    private javax.swing.JLabel labelHargaSize;
    private javax.swing.JLabel labelHargaTopping;
    private javax.swing.JLabel labelHargaTotal;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelSweetness;
    private javax.swing.JLabel labelTopping;
    private javax.swing.JLabel latar;
    private javax.swing.JLabel outputDairy;
    private javax.swing.JLabel outputHotIce;
    private javax.swing.JLabel outputMenu;
    private javax.swing.JLabel outputNama;
    private javax.swing.JLabel outputNotes;
    private javax.swing.JLabel outputSize;
    private javax.swing.JLabel outputSweetness;
    private javax.swing.JLabel outputTopping;
    private javax.swing.JPanel panelDairy;
    private javax.swing.JPanel panelHarga;
    private javax.swing.JPanel panelHotIce;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNote;
    private javax.swing.JPanel panelTotalPrice;
    private javax.swing.JButton tombolGrab;
    // End of variables declaration//GEN-END:variables
        
    //OUTPUT LABEL
    public void getOutputNama() {
        String oNama = data.getNama();
        outputNama.setText("Here's Your Order, " + oNama);
    }
    
    public void getOutputMenu() {
        String oMenu = data.getMenu();
        outputMenu.setText(oMenu);
    }
    
    public void getOutputSize() {
        String oSize = data.getSize();
        outputSize.setText(oSize);
    }
    
    public void getOutputDairy() {
        String oDairy = data.getDairy();
        outputDairy.setText(oDairy);
    }
    
    public void getOutputTopping() {
        String oTopping = data.getTopping();
        outputTopping.setText(oTopping);
    }
      
    public void getOutputHotIce() {
        String oHotIce = data.getHotIce();
        outputHotIce.setText(oHotIce);
    }
    
    public void getOutputSweetness() {
        String oSweetness = data.getSweetness();
        outputSweetness.setText(oSweetness);
    }
    
    public void getOutputNotes() {
        String oNotes = data.getNotes();
        outputNotes.setText(oNotes);
    }

    //OUTPUT HARGA
    public void getHargaDefault() {
        int hdefault = controller.gethDefault(data.getMenu());
        hargaDefault.setText("Rp " + hdefault);
    }
    
    public void getHargaSize() {
        int hSize = controller.gethSize(data.getSize());
        hargaSize.setText("Rp " + hSize);
    }
   
    public void getHargaDairy() {
        int hDairy = controller.gethDairy(data.getDairy());
        hargaDairy.setText("Rp " + hDairy);
    }
    
    public void getHargaTopping() {
        int hTopping = controller.gethTopping(data.getTopping());
        hargaTopping.setText("Rp " + hTopping);
    }

    public void getHargaTotal() {
    int hDefault = controller.gethDefault(data.getMenu());
    int hSize = controller.gethSize(data.getSize());
    int hDairy = controller.gethDairy(data.getDairy());
    int hTopping = controller.gethTopping(data.getTopping());

    int hTotal = hDefault + hSize + hDairy + hTopping;
    hargaTotal.setText("Rp " + hTotal);
    
    controller1.updateTotalHarga(idRiwayat, hTotal);
    }

}
